# Cloudflare Workers config for serving the VitePress docs site

name = "anibridge-docs"
main = "src/worker.ts"
compatibility_date = "2025-08-15"

# Serve the prebuilt VitePress output as static assets.
# The Pages build step will run the docs build. Avoid duplicate builds here.

# Static asset directory produced by VitePress: docs/.vitepress/dist
[assets]
directory = "docs/.vitepress/dist"
# binding defaults to "ASSETS"; set explicitly for clarity
binding = "ASSETS"

# By default this deploys to <name>.<your-account>.workers.dev
# To use a custom domain or route, uncomment and set your zone and pattern:
# routes = [
#   { pattern = "docs.example.com", zone_name = "example.com" },
#   # or a path-based route on a zone
#   # { pattern = "example.com/docs*", zone_name = "example.com" }
# ]

# Optional environment overrides (example for production). Remove if unused.
# [env.production]
# routes = [
#   { pattern = "docs.example.com", zone_name = "example.com" }
# ]
