# Cloudflare Workers config for serving the VitePress docs site

name = "anibridge-docs"
main = "src/worker.ts"
compatibility_date = "2025-08-15"
routes = [
  { pattern = "anibridge-docs.zacklack.de", zone_name = "zacklack.de" }
]

# Build the VitePress site under docs/ and serve the output as static assets.
[build]
# Ensure docs deps are installed, then build VitePress
command = "npm --prefix docs ci --no-audit --no-fund && npm --prefix docs run build"
# Watch only content/config to avoid loops from node_modules or dist changes
watch_dir = [
  "docs/src",
  "docs/.vitepress/config.mts",
  "docs/.vitepress/theme"
]

# Static asset directory produced by VitePress: docs/.vitepress/dist
[assets]
directory = "docs/.vitepress/dist"
# binding defaults to "ASSETS"; set explicitly for clarity
binding = "ASSETS"

# By default this deploys to <name>.<your-account>.workers.dev
# To use a custom domain or route, uncomment and set your zone and pattern:

# Optional environment overrides (example for production). Remove if unused.
# [env.production]
# routes = [
#   { pattern = "docs.example.com", zone_name = "example.com" }
# ]
