export default {
  async fetch(request: Request, env: { ASSETS: Fetcher }, _ctx: ExecutionContext): Promise<Response> {
    // Delegate all requests to the static asset server generated by wrangler's [assets] config.
    // This serves files from docs/.vitepress/dist with correct content types and caching.
    return env.ASSETS.fetch(request);
  },
};

